// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const configureAssessment = `-- name: ConfigureAssessment :execrows
UPDATE automation_settings
SET automatic_assessment_enabled = ?1,
    assessment_processing_limit = ?2,
    updated_at = ?3
WHERE id = 1
`

type ConfigureAssessmentParams struct {
	AutomaticAssessmentEnabled int64
	AssessmentProcessingLimit  int64
	UpdatedAt                  int64
}

func (q *Queries) ConfigureAssessment(ctx context.Context, arg ConfigureAssessmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, configureAssessment, arg.AutomaticAssessmentEnabled, arg.AssessmentProcessingLimit, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ensureSafeDefaults = `-- name: EnsureSafeDefaults :exec
INSERT OR IGNORE INTO automation_settings (
  id,
  automatic_assessment_enabled,
  assessment_processing_limit,
  automatic_outreach_enabled,
  outreach_greeting_text,
  outreach_time_windows_json,
  updated_at
) VALUES (1, 0, 5, 0, NULL, '[]', ?1)
`

func (q *Queries) EnsureSafeDefaults(ctx context.Context, updatedAt int64) error {
	_, err := q.db.ExecContext(ctx, ensureSafeDefaults, updatedAt)
	return err
}

const getAutomationSettings = `-- name: GetAutomationSettings :one
SELECT
  automatic_assessment_enabled,
  assessment_processing_limit,
  automatic_outreach_enabled,
  outreach_greeting_text,
  outreach_time_windows_json
FROM automation_settings
WHERE id = 1
`

type GetAutomationSettingsRow struct {
	AutomaticAssessmentEnabled int64
	AssessmentProcessingLimit  int64
	AutomaticOutreachEnabled   int64
	OutreachGreetingText       sql.NullString
	OutreachTimeWindowsJson    string
}

func (q *Queries) GetAutomationSettings(ctx context.Context) (GetAutomationSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getAutomationSettings)
	var i GetAutomationSettingsRow
	err := row.Scan(
		&i.AutomaticAssessmentEnabled,
		&i.AssessmentProcessingLimit,
		&i.AutomaticOutreachEnabled,
		&i.OutreachGreetingText,
		&i.OutreachTimeWindowsJson,
	)
	return i, err
}
