// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

import (
	"database/sql"
)

type AssessmentPolicyVersion struct {
	ID         int64
	VersionNo  int64
	RulesJson  string
	IsActive   int64
	ChangeNote sql.NullString
	CreatedAt  int64
}

type AutomationSetting struct {
	ID                         int64
	AutomaticAssessmentEnabled int64
	AssessmentProcessingLimit  int64
	AutomaticOutreachEnabled   int64
	OutreachGreetingText       sql.NullString
	OutreachTimeWindowsJson    string
	UpdatedAt                  int64
}

type DiscoveryRun struct {
	ID                      int64
	Name                    sql.NullString
	ResumeVersionID         sql.NullInt64
	CurrentRole             sql.NullString
	CurrentCity             sql.NullString
	NextPage                sql.NullInt64
	Status                  string
	AttemptNo               int64
	ConsecutiveFailureCount int64
	RetryAt                 sql.NullInt64
	WorkerOwner             sql.NullString
	WorkerLeaseUntil        sql.NullInt64
	CreatedAt               int64
	PreparedAt              sql.NullInt64
	LastProgressAt          sql.NullInt64
	FinishedAt              sql.NullInt64
	UpdatedAt               int64
}

type OnlineResumeVersion struct {
	ID         int64
	VersionNo  int64
	ResumeJson string
	ResumeHash string
	IsCurrent  int64
	CreatedAt  int64
}

type PlatformJob struct {
	ID                                int64
	PlatformJobID                     string
	CanonicalUrl                      string
	JobTitle                          string
	CompanyName                       sql.NullString
	CityText                          sql.NullString
	SalaryText                        sql.NullString
	JdJson                            string
	JdHash                            string
	PlatformStatus                    string
	PlatformClosedReason              sql.NullString
	PlatformStatusCheckedAt           int64
	AssessmentStatus                  string
	AssessmentResumeVersionID         sql.NullInt64
	AssessmentJdHash                  sql.NullString
	AssessmentPolicyVersionID         sql.NullInt64
	EvaluatorVersion                  sql.NullInt64
	AssessmentAttemptNo               int64
	AssessmentConsecutiveFailureCount int64
	AssessmentReason                  sql.NullString
	AssessmentEvidenceJson            sql.NullString
	AssessmentRetryAt                 sql.NullInt64
	AssessedAt                        sql.NullInt64
	HumanVerdict                      sql.NullString
	HumanReviewedJdHash               sql.NullString
	HumanReviewedAt                   sql.NullInt64
	HumanReviewNote                   sql.NullString
	OutreachStatus                    string
	OutreachGreetingText              sql.NullString
	OutreachAttemptNo                 int64
	OutreachConsecutiveFailureCount   int64
	OutreachLastAttemptAt             sql.NullInt64
	OutreachRetryAt                   sql.NullInt64
	OutreachEvidenceJson              sql.NullString
	ContactSource                     sql.NullString
	ContactedAt                       sql.NullInt64
	LeaseStage                        sql.NullString
	LeaseOwner                        sql.NullString
	LeaseUntil                        sql.NullInt64
	FirstSeenAt                       int64
	LastSeenAt                        int64
	UpdatedAt                         int64
}
