// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const listPlatformJobs = `-- name: ListPlatformJobs :many
SELECT
    id,
    platform_job_id,
    canonical_url,
    job_title,
    company_name,
    city_text,
    salary_text,
    jd_json,
    jd_hash,
    platform_status,
    platform_closed_reason,
    platform_status_checked_at,
    first_seen_at,
    last_seen_at,
    updated_at
FROM platform_jobs
ORDER BY first_seen_at, id
`

type ListPlatformJobsRow struct {
	ID                      int64
	PlatformJobID           string
	CanonicalUrl            string
	JobTitle                string
	CompanyName             sql.NullString
	CityText                sql.NullString
	SalaryText              sql.NullString
	JdJson                  string
	JdHash                  string
	PlatformStatus          string
	PlatformClosedReason    sql.NullString
	PlatformStatusCheckedAt int64
	FirstSeenAt             int64
	LastSeenAt              int64
	UpdatedAt               int64
}

func (q *Queries) ListPlatformJobs(ctx context.Context) ([]ListPlatformJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlatformJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlatformJobsRow
	for rows.Next() {
		var i ListPlatformJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlatformJobID,
			&i.CanonicalUrl,
			&i.JobTitle,
			&i.CompanyName,
			&i.CityText,
			&i.SalaryText,
			&i.JdJson,
			&i.JdHash,
			&i.PlatformStatus,
			&i.PlatformClosedReason,
			&i.PlatformStatusCheckedAt,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const observePlatformJob = `-- name: ObservePlatformJob :one
INSERT INTO platform_jobs (
    platform_job_id,
    canonical_url,
    job_title,
    company_name,
    city_text,
    salary_text,
    jd_json,
    jd_hash,
    platform_status,
    platform_closed_reason,
    platform_status_checked_at,
    first_seen_at,
    last_seen_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(platform_job_id) DO UPDATE SET
    canonical_url = excluded.canonical_url,
    job_title = excluded.job_title,
    company_name = excluded.company_name,
    city_text = excluded.city_text,
    salary_text = excluded.salary_text,
    jd_json = excluded.jd_json,
    jd_hash = excluded.jd_hash,
    platform_status = excluded.platform_status,
    platform_closed_reason = excluded.platform_closed_reason,
    platform_status_checked_at = excluded.platform_status_checked_at,
    last_seen_at = excluded.last_seen_at,
    updated_at = excluded.updated_at
RETURNING
    id,
    platform_job_id,
    canonical_url,
    job_title,
    company_name,
    city_text,
    salary_text,
    jd_json,
    jd_hash,
    platform_status,
    platform_closed_reason,
    platform_status_checked_at,
    first_seen_at,
    last_seen_at,
    updated_at
`

type ObservePlatformJobParams struct {
	PlatformJobID           string
	CanonicalUrl            string
	JobTitle                string
	CompanyName             sql.NullString
	CityText                sql.NullString
	SalaryText              sql.NullString
	JdJson                  string
	JdHash                  string
	PlatformStatus          string
	PlatformClosedReason    sql.NullString
	PlatformStatusCheckedAt int64
	FirstSeenAt             int64
	LastSeenAt              int64
	UpdatedAt               int64
}

type ObservePlatformJobRow struct {
	ID                      int64
	PlatformJobID           string
	CanonicalUrl            string
	JobTitle                string
	CompanyName             sql.NullString
	CityText                sql.NullString
	SalaryText              sql.NullString
	JdJson                  string
	JdHash                  string
	PlatformStatus          string
	PlatformClosedReason    sql.NullString
	PlatformStatusCheckedAt int64
	FirstSeenAt             int64
	LastSeenAt              int64
	UpdatedAt               int64
}

func (q *Queries) ObservePlatformJob(ctx context.Context, arg ObservePlatformJobParams) (ObservePlatformJobRow, error) {
	row := q.db.QueryRowContext(ctx, observePlatformJob,
		arg.PlatformJobID,
		arg.CanonicalUrl,
		arg.JobTitle,
		arg.CompanyName,
		arg.CityText,
		arg.SalaryText,
		arg.JdJson,
		arg.JdHash,
		arg.PlatformStatus,
		arg.PlatformClosedReason,
		arg.PlatformStatusCheckedAt,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.UpdatedAt,
	)
	var i ObservePlatformJobRow
	err := row.Scan(
		&i.ID,
		&i.PlatformJobID,
		&i.CanonicalUrl,
		&i.JobTitle,
		&i.CompanyName,
		&i.CityText,
		&i.SalaryText,
		&i.JdJson,
		&i.JdHash,
		&i.PlatformStatus,
		&i.PlatformClosedReason,
		&i.PlatformStatusCheckedAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}
