// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlitedb

import (
	"context"
)

const getActiveDiscoveryResumeUse = `-- name: GetActiveDiscoveryResumeUse :one
SELECT
    discovery_runs.id AS discovery_run_id,
    online_resume_versions.version_no AS resume_version_no
FROM discovery_runs
JOIN online_resume_versions
    ON online_resume_versions.id = discovery_runs.resume_version_id
WHERE discovery_runs.status IN ('preparing', 'running', 'paused', 'failed')
ORDER BY discovery_runs.id DESC
LIMIT 1
`

type GetActiveDiscoveryResumeUseRow struct {
	DiscoveryRunID  int64
	ResumeVersionNo int64
}

func (q *Queries) GetActiveDiscoveryResumeUse(ctx context.Context) (GetActiveDiscoveryResumeUseRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveDiscoveryResumeUse)
	var i GetActiveDiscoveryResumeUseRow
	err := row.Scan(&i.DiscoveryRunID, &i.ResumeVersionNo)
	return i, err
}
