// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const advanceDiscoveryJob = `-- name: AdvanceDiscoveryJob :one
UPDATE discovery_runs
SET next_job_ordinal = ?1,
    consecutive_failure_count = 0,
    last_progress_at = ?2,
    worker_lease_until = ?3,
    updated_at = ?4
WHERE id = ?5
  AND status = 'running'
  AND attempt_no = ?6
  AND worker_owner = ?7
  AND current_role = ?8
  AND current_city = ?9
  AND next_page = ?10
  AND current_page_job_ids_json = ?11
  AND current_page_has_more = ?12
  AND next_job_ordinal = ?13
  AND json_extract(
        current_page_job_ids_json,
        '$[' || next_job_ordinal || ']'
      ) = ?14
RETURNING id
`

type AdvanceDiscoveryJobParams struct {
	NextJobOrdinal    sql.NullInt64
	ProgressAt        sql.NullInt64
	WorkerLeaseUntil  sql.NullInt64
	UpdatedAt         int64
	RunID             int64
	AttemptNo         int64
	WorkerOwner       sql.NullString
	CurrentRole       sql.NullString
	CurrentCity       sql.NullString
	CurrentPage       sql.NullInt64
	JobIdsJson        sql.NullString
	HasMore           sql.NullInt64
	CurrentJobOrdinal sql.NullInt64
	PlatformJobID     sql.NullString
}

func (q *Queries) AdvanceDiscoveryJob(ctx context.Context, arg AdvanceDiscoveryJobParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, advanceDiscoveryJob,
		arg.NextJobOrdinal,
		arg.ProgressAt,
		arg.WorkerLeaseUntil,
		arg.UpdatedAt,
		arg.RunID,
		arg.AttemptNo,
		arg.WorkerOwner,
		arg.CurrentRole,
		arg.CurrentCity,
		arg.CurrentPage,
		arg.JobIdsJson,
		arg.HasMore,
		arg.CurrentJobOrdinal,
		arg.PlatformJobID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const advanceDiscoveryPage = `-- name: AdvanceDiscoveryPage :one
UPDATE discovery_runs
SET next_page = ?1,
    current_page_job_ids_json = NULL,
    current_page_has_more = NULL,
    next_job_ordinal = NULL,
    consecutive_failure_count = 0,
    last_progress_at = ?2,
    worker_lease_until = ?3,
    updated_at = ?4
WHERE id = ?5
  AND status = 'running'
  AND attempt_no = ?6
  AND worker_owner = ?7
  AND current_role = ?8
  AND current_city = ?9
  AND next_page = ?10
  AND current_page_job_ids_json IS NOT NULL
  AND next_job_ordinal = json_array_length(current_page_job_ids_json)
RETURNING id
`

type AdvanceDiscoveryPageParams struct {
	NextPage         sql.NullInt64
	ProgressAt       sql.NullInt64
	WorkerLeaseUntil sql.NullInt64
	UpdatedAt        int64
	RunID            int64
	AttemptNo        int64
	WorkerOwner      sql.NullString
	CurrentRole      sql.NullString
	CurrentCity      sql.NullString
	CurrentPage      sql.NullInt64
}

func (q *Queries) AdvanceDiscoveryPage(ctx context.Context, arg AdvanceDiscoveryPageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, advanceDiscoveryPage,
		arg.NextPage,
		arg.ProgressAt,
		arg.WorkerLeaseUntil,
		arg.UpdatedAt,
		arg.RunID,
		arg.AttemptNo,
		arg.WorkerOwner,
		arg.CurrentRole,
		arg.CurrentCity,
		arg.CurrentPage,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const claimDueDiscoveryRetry = `-- name: ClaimDueDiscoveryRetry :one
UPDATE discovery_runs
SET status = 'running',
    attempt_no = attempt_no + 1,
    retry_at = NULL,
    worker_owner = ?1,
    worker_lease_until = ?2,
    updated_at = ?3
WHERE id = ?4
  AND status = 'failed'
  AND retry_at IS NOT NULL
  AND retry_at <= ?5
RETURNING attempt_no
`

type ClaimDueDiscoveryRetryParams struct {
	WorkerOwner      sql.NullString
	WorkerLeaseUntil sql.NullInt64
	UpdatedAt        int64
	RunID            int64
	Now              sql.NullInt64
}

func (q *Queries) ClaimDueDiscoveryRetry(ctx context.Context, arg ClaimDueDiscoveryRetryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, claimDueDiscoveryRetry,
		arg.WorkerOwner,
		arg.WorkerLeaseUntil,
		arg.UpdatedAt,
		arg.RunID,
		arg.Now,
	)
	var attempt_no int64
	err := row.Scan(&attempt_no)
	return attempt_no, err
}

const completeDiscoveryRun = `-- name: CompleteDiscoveryRun :one
UPDATE discovery_runs
SET status = 'completed',
    current_page_job_ids_json = NULL,
    current_page_has_more = NULL,
    next_job_ordinal = NULL,
    consecutive_failure_count = 0,
    retry_at = NULL,
    worker_owner = NULL,
    worker_lease_until = NULL,
    last_progress_at = ?1,
    finished_at = ?2,
    updated_at = ?3
WHERE id = ?4
  AND status = 'running'
  AND attempt_no = ?5
  AND worker_owner = ?6
  AND current_role = ?7
  AND current_city = ?8
  AND next_page = ?9
  AND current_page_job_ids_json IS NOT NULL
  AND next_job_ordinal = json_array_length(current_page_job_ids_json)
RETURNING id
`

type CompleteDiscoveryRunParams struct {
	ProgressAt  sql.NullInt64
	FinishedAt  sql.NullInt64
	UpdatedAt   int64
	RunID       int64
	AttemptNo   int64
	WorkerOwner sql.NullString
	CurrentRole sql.NullString
	CurrentCity sql.NullString
	CurrentPage sql.NullInt64
}

func (q *Queries) CompleteDiscoveryRun(ctx context.Context, arg CompleteDiscoveryRunParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, completeDiscoveryRun,
		arg.ProgressAt,
		arg.FinishedAt,
		arg.UpdatedAt,
		arg.RunID,
		arg.AttemptNo,
		arg.WorkerOwner,
		arg.CurrentRole,
		arg.CurrentCity,
		arg.CurrentPage,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const continueDiscoveryRun = `-- name: ContinueDiscoveryRun :one
UPDATE discovery_runs
SET status = 'running',
    attempt_no = attempt_no + 1,
    consecutive_failure_count = 0,
    retry_at = NULL,
    worker_owner = ?1,
    worker_lease_until = ?2,
    updated_at = ?3
WHERE id = ?4
  AND status IN ('paused', 'failed')
  AND resume_version_id IS NOT NULL
  AND current_role IS NOT NULL
  AND current_city IS NOT NULL
  AND next_page IS NOT NULL
RETURNING attempt_no
`

type ContinueDiscoveryRunParams struct {
	WorkerOwner      sql.NullString
	WorkerLeaseUntil sql.NullInt64
	UpdatedAt        int64
	RunID            int64
}

func (q *Queries) ContinueDiscoveryRun(ctx context.Context, arg ContinueDiscoveryRunParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, continueDiscoveryRun,
		arg.WorkerOwner,
		arg.WorkerLeaseUntil,
		arg.UpdatedAt,
		arg.RunID,
	)
	var attempt_no int64
	err := row.Scan(&attempt_no)
	return attempt_no, err
}

const createDiscoveryRun = `-- name: CreateDiscoveryRun :one
INSERT INTO discovery_runs (
    resume_version_id,
    current_role,
    current_city,
    next_page,
    status,
    attempt_no,
    worker_owner,
    worker_lease_until,
    created_at,
    prepared_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    1,
    'running',
    1,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8
)
RETURNING id
`

type CreateDiscoveryRunParams struct {
	ResumeVersionID  sql.NullInt64
	CurrentRole      sql.NullString
	CurrentCity      sql.NullString
	WorkerOwner      sql.NullString
	WorkerLeaseUntil sql.NullInt64
	CreatedAt        int64
	PreparedAt       sql.NullInt64
	UpdatedAt        int64
}

func (q *Queries) CreateDiscoveryRun(ctx context.Context, arg CreateDiscoveryRunParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createDiscoveryRun,
		arg.ResumeVersionID,
		arg.CurrentRole,
		arg.CurrentCity,
		arg.WorkerOwner,
		arg.WorkerLeaseUntil,
		arg.CreatedAt,
		arg.PreparedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const endDiscoveryRunEarly = `-- name: EndDiscoveryRunEarly :one
UPDATE discovery_runs
SET status = 'ended_early',
    current_page_job_ids_json = NULL,
    current_page_has_more = NULL,
    next_job_ordinal = NULL,
    retry_at = NULL,
    worker_owner = NULL,
    worker_lease_until = NULL,
    finished_at = ?1,
    updated_at = ?2
WHERE id = ?3
  AND status IN ('preparing', 'running', 'paused', 'failed')
RETURNING id
`

type EndDiscoveryRunEarlyParams struct {
	FinishedAt sql.NullInt64
	UpdatedAt  int64
	RunID      int64
}

func (q *Queries) EndDiscoveryRunEarly(ctx context.Context, arg EndDiscoveryRunEarlyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, endDiscoveryRunEarly, arg.FinishedAt, arg.UpdatedAt, arg.RunID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const expireDiscoveryWorker = `-- name: ExpireDiscoveryWorker :one
UPDATE discovery_runs
SET status = 'failed',
    consecutive_failure_count = consecutive_failure_count + 1,
    retry_at = NULL,
    worker_owner = NULL,
    worker_lease_until = NULL,
    updated_at = ?1
WHERE id = ?2
  AND status = 'running'
  AND worker_owner <> ?3
  AND worker_lease_until IS NOT NULL
  AND worker_lease_until <= ?4
RETURNING id
`

type ExpireDiscoveryWorkerParams struct {
	UpdatedAt          int64
	RunID              int64
	CurrentWorkerOwner sql.NullString
	Now                sql.NullInt64
}

func (q *Queries) ExpireDiscoveryWorker(ctx context.Context, arg ExpireDiscoveryWorkerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, expireDiscoveryWorker,
		arg.UpdatedAt,
		arg.RunID,
		arg.CurrentWorkerOwner,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const failDiscoveryRun = `-- name: FailDiscoveryRun :one
UPDATE discovery_runs
SET status = 'failed',
    consecutive_failure_count = consecutive_failure_count + 1,
    retry_at = ?1,
    worker_owner = NULL,
    worker_lease_until = NULL,
    updated_at = ?2
WHERE id = ?3
  AND status = 'running'
  AND attempt_no = ?4
  AND worker_owner = ?5
RETURNING id
`

type FailDiscoveryRunParams struct {
	RetryAt     sql.NullInt64
	UpdatedAt   int64
	RunID       int64
	AttemptNo   int64
	WorkerOwner sql.NullString
}

func (q *Queries) FailDiscoveryRun(ctx context.Context, arg FailDiscoveryRunParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, failDiscoveryRun,
		arg.RetryAt,
		arg.UpdatedAt,
		arg.RunID,
		arg.AttemptNo,
		arg.WorkerOwner,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const freezeDiscoveryPage = `-- name: FreezeDiscoveryPage :one
UPDATE discovery_runs
SET current_page_job_ids_json = ?1,
    current_page_has_more = ?2,
    next_job_ordinal = 0,
    consecutive_failure_count = 0,
    last_progress_at = ?3,
    worker_lease_until = ?4,
    updated_at = ?5
WHERE id = ?6
  AND status = 'running'
  AND attempt_no = ?7
  AND worker_owner = ?8
  AND current_role = ?9
  AND current_city = ?10
  AND next_page = ?11
  AND current_page_job_ids_json IS NULL
  AND current_page_has_more IS NULL
  AND next_job_ordinal IS NULL
RETURNING id
`

type FreezeDiscoveryPageParams struct {
	JobIdsJson       sql.NullString
	HasMore          sql.NullInt64
	ProgressAt       sql.NullInt64
	WorkerLeaseUntil sql.NullInt64
	UpdatedAt        int64
	RunID            int64
	AttemptNo        int64
	WorkerOwner      sql.NullString
	CurrentRole      sql.NullString
	CurrentCity      sql.NullString
	NextPage         sql.NullInt64
}

func (q *Queries) FreezeDiscoveryPage(ctx context.Context, arg FreezeDiscoveryPageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, freezeDiscoveryPage,
		arg.JobIdsJson,
		arg.HasMore,
		arg.ProgressAt,
		arg.WorkerLeaseUntil,
		arg.UpdatedAt,
		arg.RunID,
		arg.AttemptNo,
		arg.WorkerOwner,
		arg.CurrentRole,
		arg.CurrentCity,
		arg.NextPage,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getActiveDiscoveryResumeUse = `-- name: GetActiveDiscoveryResumeUse :one
SELECT
    discovery_runs.id AS discovery_run_id,
    COALESCE(online_resume_versions.version_no, 0) AS resume_version_no
FROM discovery_runs
LEFT JOIN online_resume_versions
    ON online_resume_versions.id = discovery_runs.resume_version_id
WHERE discovery_runs.status IN ('preparing', 'running', 'paused', 'failed')
ORDER BY discovery_runs.id DESC
LIMIT 1
`

type GetActiveDiscoveryResumeUseRow struct {
	DiscoveryRunID  int64
	ResumeVersionNo int64
}

func (q *Queries) GetActiveDiscoveryResumeUse(ctx context.Context) (GetActiveDiscoveryResumeUseRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveDiscoveryResumeUse)
	var i GetActiveDiscoveryResumeUseRow
	err := row.Scan(&i.DiscoveryRunID, &i.ResumeVersionNo)
	return i, err
}

const getLatestDiscoveryRun = `-- name: GetLatestDiscoveryRun :one
SELECT
    discovery_runs.id,
    discovery_runs.current_role,
    discovery_runs.current_city,
    discovery_runs.next_page,
    discovery_runs.status,
    discovery_runs.attempt_no,
    discovery_runs.consecutive_failure_count,
    discovery_runs.retry_at,
    discovery_runs.worker_owner,
    discovery_runs.worker_lease_until,
    discovery_runs.current_page_job_ids_json,
    discovery_runs.current_page_has_more,
    discovery_runs.next_job_ordinal,
    COALESCE(online_resume_versions.version_no, 0) AS resume_version_no,
    COALESCE(online_resume_versions.resume_json, '') AS resume_json
FROM discovery_runs
LEFT JOIN online_resume_versions
    ON online_resume_versions.id = discovery_runs.resume_version_id
ORDER BY discovery_runs.id DESC
LIMIT 1
`

type GetLatestDiscoveryRunRow struct {
	ID                      int64
	CurrentRole             sql.NullString
	CurrentCity             sql.NullString
	NextPage                sql.NullInt64
	Status                  string
	AttemptNo               int64
	ConsecutiveFailureCount int64
	RetryAt                 sql.NullInt64
	WorkerOwner             sql.NullString
	WorkerLeaseUntil        sql.NullInt64
	CurrentPageJobIdsJson   sql.NullString
	CurrentPageHasMore      sql.NullInt64
	NextJobOrdinal          sql.NullInt64
	ResumeVersionNo         int64
	ResumeJson              string
}

func (q *Queries) GetLatestDiscoveryRun(ctx context.Context) (GetLatestDiscoveryRunRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestDiscoveryRun)
	var i GetLatestDiscoveryRunRow
	err := row.Scan(
		&i.ID,
		&i.CurrentRole,
		&i.CurrentCity,
		&i.NextPage,
		&i.Status,
		&i.AttemptNo,
		&i.ConsecutiveFailureCount,
		&i.RetryAt,
		&i.WorkerOwner,
		&i.WorkerLeaseUntil,
		&i.CurrentPageJobIdsJson,
		&i.CurrentPageHasMore,
		&i.NextJobOrdinal,
		&i.ResumeVersionNo,
		&i.ResumeJson,
	)
	return i, err
}

const lockCurrentDiscoveryJob = `-- name: LockCurrentDiscoveryJob :one
UPDATE discovery_runs
SET worker_lease_until = worker_lease_until
WHERE id = ?1
  AND status = 'running'
  AND attempt_no = ?2
  AND worker_owner = ?3
  AND current_role = ?4
  AND current_city = ?5
  AND next_page = ?6
  AND current_page_job_ids_json = ?7
  AND current_page_has_more = ?8
  AND next_job_ordinal = ?9
  AND json_extract(
        current_page_job_ids_json,
        '$[' || next_job_ordinal || ']'
      ) = ?10
RETURNING id
`

type LockCurrentDiscoveryJobParams struct {
	RunID         int64
	AttemptNo     int64
	WorkerOwner   sql.NullString
	CurrentRole   sql.NullString
	CurrentCity   sql.NullString
	NextPage      sql.NullInt64
	JobIdsJson    sql.NullString
	HasMore       sql.NullInt64
	JobOrdinal    sql.NullInt64
	PlatformJobID sql.NullString
}

func (q *Queries) LockCurrentDiscoveryJob(ctx context.Context, arg LockCurrentDiscoveryJobParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, lockCurrentDiscoveryJob,
		arg.RunID,
		arg.AttemptNo,
		arg.WorkerOwner,
		arg.CurrentRole,
		arg.CurrentCity,
		arg.NextPage,
		arg.JobIdsJson,
		arg.HasMore,
		arg.JobOrdinal,
		arg.PlatformJobID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const pauseDiscoveryRun = `-- name: PauseDiscoveryRun :one
UPDATE discovery_runs
SET status = 'paused',
    retry_at = NULL,
    worker_owner = NULL,
    worker_lease_until = NULL,
    updated_at = ?1
WHERE id = ?2
  AND status = 'running'
RETURNING id
`

type PauseDiscoveryRunParams struct {
	UpdatedAt int64
	RunID     int64
}

func (q *Queries) PauseDiscoveryRun(ctx context.Context, arg PauseDiscoveryRunParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, pauseDiscoveryRun, arg.UpdatedAt, arg.RunID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const switchDiscoveryRange = `-- name: SwitchDiscoveryRange :one
UPDATE discovery_runs
SET current_role = ?1,
    current_city = ?2,
    next_page = 1,
    current_page_job_ids_json = NULL,
    current_page_has_more = NULL,
    next_job_ordinal = NULL,
    consecutive_failure_count = 0,
    last_progress_at = ?3,
    worker_lease_until = ?4,
    updated_at = ?5
WHERE id = ?6
  AND status = 'running'
  AND attempt_no = ?7
  AND worker_owner = ?8
  AND current_role = ?9
  AND current_city = ?10
  AND next_page = ?11
  AND current_page_job_ids_json IS NOT NULL
  AND next_job_ordinal = json_array_length(current_page_job_ids_json)
RETURNING id
`

type SwitchDiscoveryRangeParams struct {
	NextRole         sql.NullString
	NextCity         sql.NullString
	ProgressAt       sql.NullInt64
	WorkerLeaseUntil sql.NullInt64
	UpdatedAt        int64
	RunID            int64
	AttemptNo        int64
	WorkerOwner      sql.NullString
	CurrentRole      sql.NullString
	CurrentCity      sql.NullString
	CurrentPage      sql.NullInt64
}

func (q *Queries) SwitchDiscoveryRange(ctx context.Context, arg SwitchDiscoveryRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, switchDiscoveryRange,
		arg.NextRole,
		arg.NextCity,
		arg.ProgressAt,
		arg.WorkerLeaseUntil,
		arg.UpdatedAt,
		arg.RunID,
		arg.AttemptNo,
		arg.WorkerOwner,
		arg.CurrentRole,
		arg.CurrentCity,
		arg.CurrentPage,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
