// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlitedb

import (
	"context"
)

const countBusinessRows = `-- name: CountBusinessRows :one
SELECT
  (SELECT count(*) FROM online_resume_versions) AS online_resume_versions,
  (SELECT count(*) FROM assessment_policy_versions) AS assessment_policy_versions,
  (SELECT count(*) FROM discovery_runs) AS discovery_runs,
  (SELECT count(*) FROM platform_jobs) AS platform_jobs,
  (SELECT count(*) FROM automation_settings) AS automation_settings
`

type CountBusinessRowsRow struct {
	OnlineResumeVersions     int64
	AssessmentPolicyVersions int64
	DiscoveryRuns            int64
	PlatformJobs             int64
	AutomationSettings       int64
}

func (q *Queries) CountBusinessRows(ctx context.Context) (CountBusinessRowsRow, error) {
	row := q.db.QueryRowContext(ctx, countBusinessRows)
	var i CountBusinessRowsRow
	err := row.Scan(
		&i.OnlineResumeVersions,
		&i.AssessmentPolicyVersions,
		&i.DiscoveryRuns,
		&i.PlatformJobs,
		&i.AutomationSettings,
	)
	return i, err
}
