#!/usr/bin/env bash
set -euo pipefail

readonly repository_root="$(cd "$(dirname "$0")/.." && pwd)"

cd "$repository_root"
if [[ ! -f sqlc.yaml ]]; then
	generated="$(
		find . \
			\( -path './.git' -o -path './.cache' -o -path './throwaway-prototypes' -o -path './tools' \) -prune \
			-o -type f -name '*.go' -exec grep -l '^// Code generated by sqlc' {} + || true
	)"
	if [[ -n "$generated" ]]; then
		printf 'sqlc-generated files exist without sqlc.yaml:\n%s\n' "$generated" >&2
		exit 1
	fi
	printf 'sqlc generation: no configuration yet; no generated files present\n'
	exit 0
fi

sqlc_binary="$($repository_root/scripts/install-tool.sh sqlc)"
temporary_directory="$(mktemp -d)"
trap 'rm -rf "$temporary_directory"' EXIT
temporary_repository="$temporary_directory/repository"
mkdir -p "$temporary_repository"

tar -cf - --exclude='./.git' --exclude='./.cache' --exclude='./var' . \
	| tar -xf - -C "$temporary_repository"

(
	cd "$temporary_repository"
	"$sqlc_binary" generate
)

if ! diff -r -q -x .git -x .cache -x var "$repository_root" "$temporary_repository"; then
	printf 'sqlc generation changed committed output:\n' >&2
	diff -r -u -x .git -x .cache -x var "$repository_root" "$temporary_repository" || true
	exit 1
fi

printf 'sqlc generation: committed output is current\n'
