// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const ensureDefaultPolicy = `-- name: EnsureDefaultPolicy :exec
INSERT OR IGNORE INTO assessment_policy_versions (
  version_no, rules_json, is_active, change_note, created_at
) VALUES (
  1, ?1, 1, ?2, ?3
)
`

type EnsureDefaultPolicyParams struct {
	RulesJson  string
	ChangeNote sql.NullString
	CreatedAt  int64
}

func (q *Queries) EnsureDefaultPolicy(ctx context.Context, arg EnsureDefaultPolicyParams) error {
	_, err := q.db.ExecContext(ctx, ensureDefaultPolicy, arg.RulesJson, arg.ChangeNote, arg.CreatedAt)
	return err
}

const getActivePolicy = `-- name: GetActivePolicy :one
SELECT version_no, rules_json, change_note
FROM assessment_policy_versions
WHERE is_active = 1
`

type GetActivePolicyRow struct {
	VersionNo  int64
	RulesJson  string
	ChangeNote sql.NullString
}

func (q *Queries) GetActivePolicy(ctx context.Context) (GetActivePolicyRow, error) {
	row := q.db.QueryRowContext(ctx, getActivePolicy)
	var i GetActivePolicyRow
	err := row.Scan(&i.VersionNo, &i.RulesJson, &i.ChangeNote)
	return i, err
}
