// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlitedb

import (
	"context"
)

const getCurrentOnlineResume = `-- name: GetCurrentOnlineResume :one
SELECT id, version_no, created_at
FROM online_resume_versions
WHERE is_current = 1
`

type GetCurrentOnlineResumeRow struct {
	ID        int64
	VersionNo int64
	CreatedAt int64
}

func (q *Queries) GetCurrentOnlineResume(ctx context.Context) (GetCurrentOnlineResumeRow, error) {
	row := q.db.QueryRowContext(ctx, getCurrentOnlineResume)
	var i GetCurrentOnlineResumeRow
	err := row.Scan(&i.ID, &i.VersionNo, &i.CreatedAt)
	return i, err
}
